CREATE TABLE PRODUCTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SKU VARCHAR(50) UNIQUE NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    CATEGORY VARCHAR(100),
    PRICE DECIMAL(10,2) NOT NULL,
    STOCK_QTY INT DEFAULT 0,
    REORDER_LEVEL INT DEFAULT 10,
    WAREHOUSE_CODE VARCHAR(20) DEFAULT 'WH-01',
    DISCONTINUED BOOLEAN DEFAULT FALSE
);

CREATE TABLE ORDERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    SUBTOTAL DECIMAL(12,2),
    TAX_AMOUNT DECIMAL(12,2),
    SHIPPING_COST DECIMAL(10,2),
    TOTAL_AMOUNT DECIMAL(12,2),
    SHIPPING_ADDRESS VARCHAR(500),
    BILLING_ADDRESS VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NOTES VARCHAR(1000)
);

CREATE TABLE ORDER_LINES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_SKU VARCHAR(50) NOT NULL,
    PRODUCT_NAME VARCHAR(200),
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    LINE_TOTAL DECIMAL(12,2),
    DISCOUNT_PERCENT DECIMAL(5,2) DEFAULT 0,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID)
);

CREATE TABLE STOCK_MOVEMENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_SKU VARCHAR(50) NOT NULL,
    QUANTITY_CHANGE INT NOT NULL,
    REASON VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
