CREATE TABLE CUSTOMERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200) UNIQUE NOT NULL,
    PHONE VARCHAR(50),
    ADDRESS VARCHAR(500),
    CUST_TIER VARCHAR(20) DEFAULT 'STANDARD',
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ACCOUNTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCT_NUM VARCHAR(50) UNIQUE NOT NULL,
    CUST_ID BIGINT NOT NULL,
    ACCT_TYPE VARCHAR(10) NOT NULL,
    BALANCE DECIMAL(15,2) DEFAULT 0.00,
    INT_RATE DECIMAL(5,4) DEFAULT 0.0000,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    OPEN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(ID)
);

CREATE TABLE TXNLOG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCT_NUM VARCHAR(50) NOT NULL,
    TXN_TYPE VARCHAR(20) NOT NULL,
    AMOUNT DECIMAL(15,2) NOT NULL,
    BAL_AFTER DECIMAL(15,2),
    TXN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DESCRIPTION VARCHAR(500)
);
