import assert from 'node:assert/strict';
import test from 'node:test';
import { checkRuntime } from './check-agentic-runtime.mjs';

const repo = 'github/gh-aw-actions/setup';
const matchingSha = '6aab9e5b5c91c615506061f09bedd81a23babe3c';
const mismatchedSha = 'afc709f45ed6a3f756eb4551856c6a9c42e15b2c';
const maintenanceSha = 'ba6380cc6e5be5d21677bebe04d52fb48e3abec7';
const header = [
  '# gh-aw-metadata: {"compiler_version":"v0.86.2"}',
  `# gh-aw-manifest: ${JSON.stringify({ actions: [{ repo, sha: matchingSha, version: 'v0.86.2' }] })}`
].join('\n');

test('accepts compiler-matched runtime pins', () => {
  assert.deepEqual(checkRuntime(`${header}\n  uses: ${repo}@${matchingSha} # v0.86.2`, 'triage.lock.yml'), []);
});

test('rejects the Dependabot version mismatch from run 34359141296', () => {
  const errors = checkRuntime(`${header}\n  uses: ${repo}@${mismatchedSha} # v0.88.0`, 'triage.lock.yml');
  assert(errors.some(error => error.includes('uses v0.88.0') && error.includes('compiled with v0.86.2')));
  assert(errors.some(error => error.includes('pin differs from the generated manifest')));
});

test('rejects a changed SHA even when its comment still matches', () => {
  const errors = checkRuntime(`${header}\n  uses: ${repo}@${mismatchedSha} # v0.86.2`, 'triage.lock.yml');
  assert.equal(errors.length, 1);
  assert.match(errors[0], /pin differs from the generated manifest/);
});

test('checks the maintenance workflow compiler header and setup-cli action', () => {
  const text = '# This file was automatically generated by pkg/workflow/maintenance_workflow.go (v0.81.6). DO NOT EDIT.\n';
  assert.deepEqual(checkRuntime(`${text}  uses: github/gh-aw-actions/setup-cli@${maintenanceSha} # v0.81.6`, 'maintenance.yml'), []);
  assert.match(checkRuntime(`${text}  uses: github/gh-aw-actions/setup-cli@${mismatchedSha} # v0.88.0`, 'maintenance.yml')[0],
    /compiled with v0.81.6/);
});

test('rejects missing version metadata or unpinned runtime actions', () => {
  assert.match(checkRuntime('jobs: {}', 'triage.lock.yml')[0], /missing gh-aw compiler version/);
  assert.match(checkRuntime(`${header}\n  uses: ${repo}@v0.86.2`, 'triage.lock.yml')[0], /needs a SHA pin/);
});
